/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface AglAddressSearch {
    'debounceTimeout': number;
    'minInputChars': number;
    'redirect': string;
  }
  interface AglAddressSearchAttributes extends StencilHTMLAttributes {
    'debounceTimeout'?: number;
    'minInputChars'?: number;
    'redirect'?: string;
  }

  interface AglSpinner {
    'text': string;
  }
  interface AglSpinnerAttributes extends StencilHTMLAttributes {
    'text'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AglAddressSearch': Components.AglAddressSearch;
    'AglSpinner': Components.AglSpinner;
  }

  interface StencilIntrinsicElements {
    'agl-address-search': Components.AglAddressSearchAttributes;
    'agl-spinner': Components.AglSpinnerAttributes;
  }


  interface HTMLAglAddressSearchElement extends Components.AglAddressSearch, HTMLStencilElement {}
  var HTMLAglAddressSearchElement: {
    prototype: HTMLAglAddressSearchElement;
    new (): HTMLAglAddressSearchElement;
  };

  interface HTMLAglSpinnerElement extends Components.AglSpinner, HTMLStencilElement {}
  var HTMLAglSpinnerElement: {
    prototype: HTMLAglSpinnerElement;
    new (): HTMLAglSpinnerElement;
  };

  interface HTMLElementTagNameMap {
    'agl-address-search': HTMLAglAddressSearchElement
    'agl-spinner': HTMLAglSpinnerElement
  }

  interface ElementTagNameMap {
    'agl-address-search': HTMLAglAddressSearchElement;
    'agl-spinner': HTMLAglSpinnerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
